package DSA_Pratices;

import java.util.ArrayList;

/*
    Given a String, ABC to return all its subsequences in an arraylist. A string is a subsequences
    of a given string that is generated by deleting some character of a given string without changing its order.
    
    INPUT: ABC
    OUTPUT: [, A, B, AB, C, AC, BC, ABC]

*/

public class SubsequenceInRecursion {
	static ArrayList<String> getSubsequence(String str) {
		
		ArrayList<String> ans = new ArrayList<>();
		
		// Base Case
		if(str.length() == 0) {
			ans.add("");
			return ans;
		}
		
		char curr = str.charAt(0);
		
		ArrayList<String> smallAns = getSubsequence(str.substring(1));
		
		for(String ss: smallAns) {
			ans.add(ss);
			ans.add(curr + ss);
		}
		return ans;	
		
	}

	public static void main(String[] args) {
		String s = "ABC";
		System.out.println(getSubsequence(s));
	}

}
